spring.application.name=andy
# Configuracion de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/TiendasMandy
spring.datasource.username=postgres
spring.datasource.password=root
# Configuracion del pool de conexiones Hikari (opcional pero recomendado)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
# Configuracion de Hibernate (opcional, si usas JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
mercadopago.access.token=TEST-6137940213024002-032817-f640fd3bdaa025b4c6e5a00d3ddc959c-264387512
mercadopago.comprador.token=TEST-2347685895648948-032819-77c6ad068d4ce50364476b477e35a1aa-396289564